export const pricingPlans = [
	{
		priceId: "",
		name: "Basic Plan",
		desc: "Perfect for new videographers",
		price: 0,
		isMostPop: false,
		features: [
			"Unlimited video uploads",
			"Customizable Templates",
			"Basic Analytics",
			"Public Galleries",
			"Download Permissions",
			"Email Support",
		],
	},
	{
		priceId: "price_1OYxkqFj9oKEERu1KfJGWxgN",
		name: "Pro Plan",
		desc: "Ideal for professionals",
		price: 12,
		isMostPop: true,
		features: [
			"Unlimited video uploads",
			"Advanced Customization",
			"Detailed Analytics",
			"Private Galleries",
			"Client Feedback Tools",
			"Priority Email Support",
		],
	},
	{
		priceId: "price_1OYxkqFj9oKEERu1NbKUxXxN",
		name: "Business Plan",
		desc: "Built for studios and agencies",
		price: 32,
		isMostPop: false,
		features: [
			"All features in Pro Plan",
			"Branded Client Portals",
			"Multi-User Access",
			"Cloud Storage",
			"Custom Domain",
			"Dedicated Support",
		],
	},
];
